# -*- coding: utf-8 -*-
"""add2no.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQBIaA9eTWHPPtdgPeHr2U1o7xRHmUMh
"""

def add_numbers(a, b):
    return a + b

def main():
    result = add_numbers(3, 5)
    print(f"The result is {result}")

if __name__ == "__main__":
    main()

